/* Repertoire — automatisch aus den MP3-Dateien in assets/intern/audio abgeleitet.
   Format der Dateinamen: "Interpret - Titel.mp3".
   Bei neuen Songs Dateien dort ablegen und diese Liste neu erzeugen. */
window.SONGS = [
  { title: "Highway to Hell",                artist: "ACDC" },
  { title: "I Put A Spell On You",           artist: "Annie Lennox" },
  { title: "Spooky",                         artist: "Atlanta Rhythm Section" },
  { title: "Can't Get Enough",               artist: "Bad Company" },
  { title: "Nutbush City Limits",            artist: "Beth & Joe" },
  { title: "Beast Of Burden",                artist: "Bette Midler" },
  { title: "Waiting for the Thunder",        artist: "Blackberry Smoke" },
  { title: "Money For Nothing",              artist: "Dire Straits" },
  { title: "Ex's & Oh's",                    artist: "Elle King" },
  { title: "Don't Stop",                     artist: "Fleetwood Mac" },
  { title: "Take Me Out",                    artist: "Franz Ferdinand" },
  { title: "All Right Now (Single Version)", artist: "Free" },
  { title: "Walking By Myself",              artist: "Gary Moore" },
  { title: "Alone",                          artist: "Heart" },
  { title: "Wicked Game",                    artist: "HIM" },
  { title: "Are You Gonna Be My Girl",       artist: "Jet" },
  { title: "Locomotive Breath",              artist: "Jethro Tull" },
  { title: "First We Take Manhattan",        artist: "Joe Cocker" },
  { title: "Don't Stop Believin'",           artist: "Journey" },
  { title: "Born To Be Wild",                artist: "Krokus" },
  { title: "Are You Gonna Go My Way",        artist: "Lenny Kravitz" },
  { title: "Mighty Quinn",                   artist: "Manfred Mann's Earth Band" },
  { title: "Tie Your Mother Down",           artist: "Queen" },
  { title: "I'm a Believer",                 artist: "Smash Mouth" },
  { title: "Born To Be Wild",                artist: "Steppenwolf" },
  { title: "Valerie",                        artist: "Teddy Swims" },
  { title: "Come Together",                  artist: "The Beatles" },
  { title: "Get Back",                       artist: "The Beatles" },
  { title: "Something",                      artist: "The Beatles" },
  { title: "Mustang Sally",                  artist: "The Commitments" },
  { title: "Brown Sugar",                    artist: "The Rolling Stones" },
  { title: "Honky Tonk Women",               artist: "The Rolling Stones" },
  { title: "Gimme Some Lovin",               artist: "The Spencer Davis Group" },
  { title: "Keep on Running",                artist: "The Spencer Davis Group" },
  { title: "Give Me One Reason",             artist: "Tracy Chapman" },
  { title: "Sometimes We Cry",               artist: "Van Morrison" },
  { title: "In the Midnight Hour",           artist: "Wilson Pickett" },
  { title: "Sharp Dressed Man",              artist: "ZZ Top" },
  { title: "Tush",                           artist: "ZZ Top" },
];
